In [1]:
import numpy as np
import matplotlib.pyplot as plt 
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]

In [8]:
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [9]:
dependent=dataset[[ 'charges']]

In [10]:
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [11]:
from sklearn.ensemble import  RandomForestRegressor

In [12]:
from sklearn.model_selection import GridSearchCV
#from sklearn.tree import DecisionTreeRegressor
param_grid = {'criterion':['squared_error','absolute_error','poisson'],
'max_features': ['sqrt','log2'],
'n_estimators':[50,100]}
grid = GridSearchCV(RandomForestRegressor(), param_grid, refit = True, verbose= 3,n_jobs=-1)
# fitting the model for grid search
grid.fit(independent, dependent)

Fitting 5 folds for each of 12 candidates, totalling 60 fits
Fitting 5 folds for each of 12 candidates, totalling 60 fits

C:\Anaconda3\Lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Anaconda3\Lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'poisson'],
                         'max_features': ['sqrt', 'log2'],
                         'n_estimators': [50, 100]},
             verbose=3)

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'poisson'],
                         'max_features': ['sqrt', 'log2'],
                         'n_estimators': [50, 100]},
             verbose=3)

In [13]:
# fittrefiting the model for grid search
grid.fit(independent, dependent)

Fitting 5 folds for each of 12 candidates, totalling 60 fits
Fitting 5 folds for each of 12 candidates, totalling 60 fits

C:\Anaconda3\Lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)
C:\Anaconda3\Lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'poisson'],
                         'max_features': ['sqrt', 'log2'],
                         'n_estimators': [50, 100]},
             verbose=3)

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'poisson'],
                         'max_features': ['sqrt', 'log2'],
                         'n_estimators': [50, 100]},
             verbose=3)

In [14]:
re=grid.cv_results_

In [15]:
table=pd.DataFrame.from_dict(re)
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.610621,0.056509,0.024585,0.013432,squared_error,sqrt,50,"{'criterion': 'squared_error', 'max_features':...",0.858563,0.776780,0.864508,0.830724,0.842166,0.834548,0.031254,2
1,1.151885,0.043980,0.043973,0.012450,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.857714,0.785798,0.861810,0.827916,0.839314,0.834511,0.027288,3
2,0.587435,0.015214,0.032180,0.015267,squared_error,log2,50,"{'criterion': 'squared_error', 'max_features':...",0.856165,0.776510,0.858748,0.827121,0.842201,0.832149,0.030021,8
3,1.305990,0.047149,0.047771,0.012913,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.856835,0.781631,0.864666,0.828282,0.842787,0.834840,0.029362,1
4,1.595011,0.020246,0.019587,0.012713,absolute_error,sqrt,50,"{'criterion': 'absolute_error', 'max_features'...",0.853767,0.770501,0.847401,0.827839,0.836381,0.827178,0.029710,12
5,3.250585,0.099789,0.049769,0.013489,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.856555,0.778784,0.855161,0.827523,0.847323,0.833069,0.029053,5
6,1.681557,0.041199,0.026384,0.016417,absolute_error,log2,50,"{'criterion': 'absolute_error', 'max_features'...",0.857302,0.777843,0.851897,0.825231,0.848237,0.832102,0.029252,9
7,3.242189,0.107617,0.055766,0.006271,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.855195,0.777325,0.852535,0.826537,0.842626,0.830844,0.028584,11
8,0.656593,0.030848,0.033379,0.011614,poisson,sqrt,50,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.858224,0.771882,0.859892,0.826960,0.841817,0.831755,0.032253,10
9,1.276808,0.029223,0.038976,0.014756,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.857060,0.776584,0.860732,0.828127,0.840270,0.832555,0.030352,6
10,0.653194,0.024172,0.039576,0.013813,poisson,log2,50,"{'criterion': 'poisson', 'max_features': 'log2...",0.855901,0.780150,0.862340,0.825437,0.838470,0.832460,0.029203,7
11,1.236433,0.107217,0.034579,0.012492,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.858161,0.781671,0.856828,0.831800,0.840850,0.833862,0.027910,4

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.610621,0.056509,0.024585,0.013432,squared_error,sqrt,50,"{'criterion': 'squared_error', 'max_features':...",0.858563,0.776780,0.864508,0.830724,0.842166,0.834548,0.031254,2
1,1.151885,0.043980,0.043973,0.012450,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.857714,0.785798,0.861810,0.827916,0.839314,0.834511,0.027288,3
2,0.587435,0.015214,0.032180,0.015267,squared_error,log2,50,"{'criterion': 'squared_error', 'max_features':...",0.856165,0.776510,0.858748,0.827121,0.842201,0.832149,0.030021,8
3,1.305990,0.047149,0.047771,0.012913,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.856835,0.781631,0.864666,0.828282,0.842787,0.834840,0.029362,1
4,1.595011,0.020246,0.019587,0.012713,absolute_error,sqrt,50,"{'criterion': 'absolute_error', 'max_features'...",0.853767,0.770501,0.847401,0.827839,0.836381,0.827178,0.029710,12
5,3.250585,0.099789,0.049769,0.013489,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.856555,0.778784,0.855161,0.827523,0.847323,0.833069,0.029053,5
6,1.681557,0.041199,0.026384,0.016417,absolute_error,log2,50,"{'criterion': 'absolute_error', 'max_features'...",0.857302,0.777843,0.851897,0.825231,0.848237,0.832102,0.029252,9
7,3.242189,0.107617,0.055766,0.006271,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.855195,0.777325,0.852535,0.826537,0.842626,0.830844,0.028584,11
8,0.656593,0.030848,0.033379,0.011614,poisson,sqrt,50,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.858224,0.771882,0.859892,0.826960,0.841817,0.831755,0.032253,10
9,1.276808,0.029223,0.038976,0.014756,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.857060,0.776584,0.860732,0.828127,0.840270,0.832555,0.030352,6
10,0.653194,0.024172,0.039576,0.013813,poisson,log2,50,"{'criterion': 'poisson', 'max_features': 'log2...",0.855901,0.780150,0.862340,0.825437,0.838470,0.832460,0.029203,7
11,1.236433,0.107217,0.034579,0.012492,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.858161,0.781671,0.856828,0.831800,0.840850,0.833862,0.027910,4

In [16]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:35
BMI:41
Children:1
Sex Male 0 or 1:1
Smoker Yes 0 or 1:0

In [17]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
#change the paramter,play with it.
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[6608.3346284]
Future_Prediction=[6608.3346284]

C:\Anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(
C:\Anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(